---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-system-passphrase-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    SYSTEM_PASSPHRASE: AgDDW+MS1J8MFnL8wPyMzq/iwXcNMckOOJcMipIAYCAoBiYN15P11KdnCRON+WJTi91aCKAwwdA/rxsjTIMQv5DT0j6ulFglLTeHBp+3dtdsG5QO2rc6DIUo32r7Z9NyCHpofSGSU2Jtn7FuNZ9FjDQ0BkdKzqbrFoQjHC2hfmAcHEjY3hq2hPboAWii/yf1tgIWrogEm35zXHMHG6zevYeamMjj+IBFOzG3zy2vrLNmy48jscJJRDMAQR5GxIlZVmfaD7+ZC9AoM0n7+0d0QDTY+owdvMdHdMNb040gdh1+YyWPNKMaYgaczYx7q/Pc8DX2itpRCmVSR0ZK6F+O8VFgcieJloNhm8b6VV60Bm1Gmp57XGKs+gVeaRzjnRjxQBsdKN1JvSEh4x5yMOJprvdyWwIx1FUyJc1caUQnzgLDL3wOmwf6Y0hGuh/nk+KU9MznH9k+afaFXTBwSgM9Alc54M7zNRVeSZu0mMMF+kTb+7FNUR86T9wV7xU9YXNdXFHnGaODFE2Z2Gl2Vv9MglmsRg4vSEYpXZv7nBKKUXOP1mxDkbK+zOfAl8X4vDWnMTUr+AEqEKyCXxSpVzw0KT/vo4LAd7g4N3VQ53dtrDNCYUK04RHNQVygdswH3XWElWV78KmB4hGu0BUqmMnkxUwPLB7K13jDuV9RcgTAm+oPMq74I8rHHZavQcneVA1bIYwodqtGiCrA6g==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-system-passphrase-secret
      namespace: b2bi-prod
    type: Opaque
