---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-system-passphrase-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    SYSTEM_PASSPHRASE: AgBoUgxe7ZwELrtmbRIS3G0F5MyyHE+COzOtSwqRmKXOXC/T8VRHqBjmxnWCQ52laU2ekUkYZflFKFB0htAdNDj0iG1w1yPDP7a8b2c0G/vZ/kP3ywWlwG51P0fSng6u5gHU8IQcxd63Yn4F15SKfrkyG6RO/rZUvOQpQmXkPdROjSSzrqQsnmPMB3MiLEHmgYEn/ek5ozxdkHDemHf0T/3+6gc1NZmOg0DukWYHimfbvFcct2BKmrDGFzurfe+3yJ93iOJ3TbrHW3HySU4Hv/dsXHlEH3/6NKC/iciLnEULOQLOsW13ceS6NRau5BY0U7snhcxZTqM5F5MPwIT+4sk9MMb8OB9Vr4W20zN7MOrf2VeY1UO0L3QhHbqs6V7inhqKcDtzgHVT+qHVpYz7qMmMfID8yTe8QbttQYtmeJ5o4gDmOdXzDy7BR8sYkBIOs6EiTqT/p0wH4Tfd1RaT0RcpljoEhseiH8FbE/BuR24YAg+cy6M6c90bstaqTlc6p+QlEHT4PuW+IpBCgB+Ytl5B9Ml+Ghk9koNongvce6bTjhggL8j90tzSP8BoAr2zb6RYc0Rys/VxH4OJRgRp3B47n9g6+tUDfXJ7x3AYhuNr61Ou6qFdfzRtxs09ERHPphDkUucYhVgMfS49vDI2xEygXb4mpXyhIJVwEKkE48/LfmsQFxl4d16A5vpqx8jly/A4aDB70CXrUg==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-system-passphrase-secret
      namespace: b2bi-prod
    type: Opaque
