---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgBVu58+okJ2vRxaFPwzhOFWEfezXLYy2lRXwLYgJnKM/jHFZ40ycFQkoe82va2WuOqJqluQXGa3CtX+h65bj+Xvx4BAV78nNNcQbX4t7731l2ukEaPkzjeGXifg1Dx3KSbjcDOpj1agqDsE8qVZ4axgvNZadnjBCgch0c5kH0etblgnTd8mppf84O/tuxGEnKeTmSNhYAalz/4nAJ/vXc7bjMKTQCT8WZxywz2dRIW0kWhrHDvVVJKGRqbo5Dg+TzFgXTwrRSwWU46Ekwns5S73TNMjWrhAwUv7iivy5jCAPyPm6U9fvNFL91gZirzOZFt7Msg3r9JcyzStcugNGjf9QiwS+iAgcEVmEcRctgI73BNC+7KFAlw2P7j7p6cq+lTCBnWWj7zwWZFUGYRZjE5Y8eeyDueyVHZ62qN4I8UB5uPQT/wyFTzD0vRVeMqsIRrhT0AVQ7M+4cxS3EGvDyM+n7G6wheYxJAfhKCekXDCom8FUaqQEh5weIIpQ6JzwySDANV5QDy9FeTsmifVN8DplkwdkuFktp7W54O6VqQteYwfQ4Xcv9pN6cYGK98RzcglrA9f2IQlkghih/3MXivLNRTf1yrb1AtifHzGZVu40QVNvWh6K2NAYMq18slwlaOBm3mTT9+4gD/Poz+Wk/jvZunnNouYJ25ifiRh7Cqg/34REYCVmY3aMlDcCGBRr6U4wwEYGPWknw==
    DB_USER: AgBRRbMOAqDBALdK2U1uqJ9YwczOPo6S7XnLrSQeMITLDtK4QqqRhcUV344TQA0PlJp/hZYUhT2vXashOzFwOYXzwXtPYxig7qp7BBIQEA1jyobFzDko0xD3VRQo6yakJXMZExqfkpSWqDNl3RtJGg1MipUWpKIaQ0Gbt2OiTZONXbipa6K+njI2eMFUTkwrT10AtzHinAJYubcOUottQaxf4KmhPBDuTIIfsQU0t7JVQDXw9vcO/4sY9jcqOrpDdBIkE5cl6bZFiKaL88mIFfqGtwNffK+d42UXyQg2hufQLEcpcRnINoJkJnZgLjqhnzVp5ADY/6hDzxQI5hMI5qgBFqMtRLy0MV3SZSss9Z9oLhwVZmJPhkW14agMxZkVzvFH4mDPM4erUBcWrdNr5BYVHdThzCxaTxesX/l5CjddIjkXHaWW0VqJv7m+4mxQyDleeVG2ggn/jOhsSVNCk0zA+3Uq+gN97GLmOIiMsLVDfJ28lbD2vaMXondPsesBotK4P+j8AEx/izWZ+1agIocy9TDou13uKUshQ/hxy6NUwPSPh7PYZ8gcHPGDlR0Esz7JI2Mz3706dc1CkUcKffl92Rvbycl1BOqsMQpUJWmXSH7mTABq0D6KVGHVuH5DkdnKL0qSCyHBiASf4HHtM2j3YQjMzHAwBLfOc4nApFdmvYB+G0cl0bq5Eg1f60JnJlhoY+1QJ5egSQ==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque
