---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgAenABBKLZEiMHYQCRQWuYE37uwq/AR5BI6OrBCFoe4p/+TltLIv/YdpdBAtTJ2iXOyiOe4YkHUOCAMdrLbzwP3RE/yKoIWpHSHh0UTrRsej7Z1kDdXZQqmiPVll86Jih9Afr+gEl9u5kI8+SdPWFpMQTY5SjY5bIo+8YnkJMQvGG8No6Cc62UT4Yp7MmBllMWite9QaEgrR05fm5ZFJhEPA6281euUmq6MEpWXrnqaa6+Mn2Mo99H+tza//rQzKTFN2cPTMrAhtsOd5HcD34kh0bAd1blq51LkjBc52eVH71pmqE2db5xRIHGD3qMGlGhBsG7z88nzAOr2UxQ35gzhHArWuXHZPWOyWEVKR7A/2+2fiaadSiRWZQlpTAGl3vU+6QmUEIUrIJdWV0fh+oYFNBAbZFNmnIPjkcWnO+KEkkDmadZBBRcUfuer6QEoTYImB3fluJmNeuHeOiOeSneNGhYMKJhIuRtGpHSGqaa5ZBbV2d27N+/d6PcXoJJ/kEIa5nioFzpZjk33S89/kBhS7R4H5+/JIulx4VCG1V5ejg62FpOFcksrTsEbvslxJ7G9c0moc+wdzQrX7t/wVmo5xZmIkA90Trbgyf77uH0G+3bQCjzHTTFyfrSEnu2qM9KtqPwksXty7WGb7oeurGhV88QLfbHIFNdFjCBVQqoMMF4FDyO72kaGnmh6IpqE1tqFARNii0ckpA==
    DB_USER: AgA2boaUzul4x0TfCwVKwnb937cQ9Plnjx2vT9oCAcV1Tp14iswNEouOUv6OQtAEgHyk0DdSlq2xufQVUB9icLNwx7Wdcx5GXv5UwiBuKfJWOhS2qGVgYpfjDQ32fplNwgM0rwpsb/ZqTMVJGVCBXZFXYyvzUHft1erUVFG4Ozrif9B9DYmg11FQI3PhXiRPD1VPk8uV0k8QpZIv7McAdVWmamXzNRmdcE90ktLKn+Rkc4kiLq4GBsdlnefCQZC0Fq/YoIyxRu4jBnZklkwYD5IiBJc9JXMzXDufvFEHn6gg7LH8VHEbT0A1ug803NhyBWQ/UWL2HvLIAlur6aeme48xPJsQQr2yqNShn3GxCVPNYMRdTtFWidt0xrqCji1QP4K3oaAODu5Nd18Dok0NQfkBmgLKkMx4S4M1IPysrUWCB9e0CMCIXT3tkNjSC8PuCfVxgofwaxy1tyui06W+TAOzliHofOwXkA1VzZaLnI6vxYdXewgba94bNHIeZcCgE6mEJMEt8NG9Z+K1ze/CdwBYSD8Y9YBGkLs7abIeZ469fpCm1MnkbuL5p8xfNAu8665xTFjGlXb1rAFduLKwzSNy/tYxq1MklRpj7I6FZt9cJbV1FVz8CNftJyRuQnT/eVd7UsyiLGEBoNGA/NkIZDFQcM5Vq5qQ8KaILjFA9sWt324UmSH2y1cPvm0tAH0fBj4eOMriTabpbw==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque
